import { Inter } from "next/font/google";
// import "./globals.css";

import EmpNav from "@/components/EmployerNav";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Habesha Net",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <EmpNav />
        {children}
        <Footer/>
    </>
    
  );
}
